MODELS:
  - "/projects/ag-bozek/bzajac/mitonet_theirw/MitoNet_checkpoint.pth.tar"
  - "/projects/ag-bozek/bzajac/mitonet_nopretrain/MitoNet-nopretraining-120_checkpoint.pth.tar"
  - "/projects/ag-bozek/bzajac/mitonet_0608/mitonet_0608-120_checkpoint.pth.tar"

ORIGINAL_MODEL: "/home/bzajac/MitoNet_v1.pth"

EVAL:
  eval_dir: "/projects/ag-bozek/bzajac/tem"
  batch_size: 1
  workers: 4
  print_freq: 50

  metrics:
    - { metric: "IoU", name: "semantic_iou", labels: [1], output_key: "sem_logits", target_key: "sem" }
    - { metric: "F1", name: "f1@50", labels: [1], label_divisor: 1000, iou_thr: 0.50, output_key: "pan_seg", target_key: "pan_seg" }
    - { metric: "F1", name: "f1@75", labels: [1], label_divisor: 1000, iou_thr: 0.75, output_key: "pan_seg", target_key: "pan_seg" }
    - { metric: "AP", name: "AP@50", labels: [1], label_divisor: 1000, iou_thr: 0.50, output_key: "pan_seg", target_key: "pan_seg" }
    - { metric: "AP", name: "AP@75", labels: [1], label_divisor: 1000, iou_thr: 0.75, output_key: "pan_seg", target_key: "pan_seg" }
    - { metric: "PQ", name: "PQ", labels: [1], label_divisor: 1000, iou_thr: 0.75, output_key: "pan_seg", target_key: "pan_seg" }
    #    - { metric: "MSA", name: "MSA", labels: [1], label_divisor: 1000, output_key: "pan_seg", target_key: "pan_seg"}
    

  engine_params:
    thing_list: [ 1 ]
    label_divisor: 1000
    stuff_area: 64
    thing_area: 150
    void_label: 0
    nms_threshold: 0.1
    nms_kernel: 7
    confidence_thr: 0.5
