MODELS:
  - "YOUR_MODEL_PATH1"
  - "YOUR_MODEL_PATH2"
# etc.
ORIGINAL_MODEL: "ORIGINAL_MODEL_PATH"

# The architecture of the models that are being benchmarked, currently mixed model benchmarking is not supported
MODELS_ARCHITECTURE:
  arch: "PanopticDeepLabPR"
  encoder: "resnet50"
  num_classes: 1
  stage4_stride: 16
  decoder_channels: 256
  low_level_stages: [ 1 ]
  low_level_channels_project: [ 32 ]
  atrous_rates: [ 2, 4, 6 ]
  aspp_channels: 256
  aspp_dropout: 0.5
  ins_decoder: True
  ins_ratio: 0.5

EVAL:
  eval_dir: "YOUR_EVAL_DIR"
  batch_size: 1
  workers: 4
  print_freq: 50

  metrics:
    - { metric: "IoU", name: "semantic_iou", labels: [1], output_key: "sem_logits", target_key: "sem" }
    - { metric: "F1", name: "f1@50", labels: [1], label_divisor: 1000, iou_thr: 0.50, output_key: "pan_seg", target_key: "pan_seg" }
    - { metric: "F1", name: "f1@75", labels: [1], label_divisor: 1000, iou_thr: 0.75, output_key: "pan_seg", target_key: "pan_seg" }
    - { metric: "AP", name: "AP@50", labels: [1], label_divisor: 1000, iou_thr: 0.50, output_key: "pan_seg", target_key: "pan_seg" }
    - { metric: "AP", name: "AP@75", labels: [1], label_divisor: 1000, iou_thr: 0.75, output_key: "pan_seg", target_key: "pan_seg" }
    - { metric: "PQ", name: "PQ", labels: [1], label_divisor: 1000, iou_thr: 0.75, output_key: "pan_seg", target_key: "pan_seg" }
#    - { metric: "MSA", name: "MSA", labels: [1], label_divisor: 1000, output_key: "pan_seg", target_key: "pan_seg"}
    
  engine_params:
    thing_list: [ 1 ]
    label_divisor: 1000
    stuff_area: 64
    # Pixel area of instance predictions to be ignored in benchmarking
    thing_area: 150
    void_label: 0
    nms_threshold: 0.1
    nms_kernel: 7
    confidence_thr: 0.5
